name: deli_hobby
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages (compatible versions)
  firebase_core: 4.3.0
  firebase_auth: 6.1.3
  cloud_firestore: 6.1.1
  firebase_storage: 13.0.5
  firebase_messaging: ^16.1.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  rxdart: ^0.27.7
  table_calendar: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true